# Generated by Django 4.2 on 2023-04-24 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_chapter_delete_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
            preserve_default=False,
        ),
    ]
