# Generated by Django 4.2 on 2023-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_chapter_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='book',
            name='bookmark',
            field=models.ManyToManyField(to='main_app.bookmark'),
        ),
    ]
